project:
  type: website

website:
  title: "Eric Ekholm"
  site-url: "https://www.ericekholm.com"
  repo-url: "https://github.com/ekholme/ee-quarto-site"
  favicon: "/img/ee-logo.png"
  
  navbar:
    pinned: true

    left:
      - about.qmd
      - blog.qmd
      - pubs.qmd
      - text: "Resume"
        href: resume.pdf
      - text: "Brain"
        href: https://ekholme.github.io/brain
      - text: "Edudata"
        href: https://edudata.blog

    right:
      - icon: github
        aria-label: github
        href: https://github.com/ekholme
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/ekholm_e
      - icon: envelope
        aria-label: email
        href: "mailto:eric.ekholm@gmail.com"
      - text: "{{< iconify simple-icons bluesky >}}"
        href: https://bsky.app/profile/ekholme.bsky.social
      - icon: rss
        href: blog.xml
      - icon: linkedin
        aria-label: linkedin
        href: https://www.linkedin.com/in/eric-ekholm-8a481022/

format:
  html:
    theme: litera
    css: styles.css

execute:
  freeze: auto

