project:
  type: website

website:
  title: "Eric Ekholm"
  site-url: "https://www.ericekholm.com"
  navbar:
    right:
      - about.qmd
      - blog.qmd
      - pubs.qmd
      - text: "Resume"
        href: resume.html
      - icon: github
        href: https://github.com/ekholme
      - icon: twitter
        href: https://twitter.com/ekholm_e
format:
  html:
    theme: litera
    css: styles.css



