---
title: "Publications"
---

This page contains a list of my academic and non-academic publications, as well as my conference presentations.


#### Academic & Peer-Reviewed Publications

Back when I was more actively involved in academia, I published some papers, mostly related to student motivation, how people write, or statistical methodology. Publishing peer-reviewed work has been less of a priority for me lately, but I still dabble here and there.

+ Senechal, J., __Ekholm, E.__, Aljudaibi, S., Strawderman, M., & Parthemos, C. (2023). [Balancing the benefits and risks of large language AI models in K12 public schools: A MERC research brief](https://merc.soe.vcu.edu/reports/research-briefs/ai-in-schools/). Richmond, VA: Metropolitan Educational Research Consortium.

+ Broda, M.D., Ross, E., Sorhagen, N., & __Ekholm, E.__ (2023). Exploring control-value motivational profiles of mathematics anxiety, self-concept, and interest in adolescents. _Frontiers in Psychology_, _14_. https://doi.org/10.3389/fpsyg.2023.1140924

+ Marrs, S., Zumbrunn, S., & __Ekholm, E.__ (2022). Measuring students' perceptions of writing feedback. _Current Research in Psychology and Behavioral Science_, _3_(4). https://doi.org/10.54026/CRPBS/1054

+ Zumbrunn, S., __Ekholm, E.__, Broda, M., & Koenka, A. C. (2022). Trajectories of students' writing feedback attitudes. _Journal of Experimental Education_. https://doi.org/10.1080/00220973.2022.2064413

+ Chow, J., __Ekholm, E.__, & Bae, C. (2021). Relative contribution of verbal working memory and attention to child language. _Assessment for Effective Intervention_, _47_(1), 3-13. http://dx.doi.org/10.1177/1534508420946361

+ Broda, M., __Ekholm, E.__, & Zumbrunn, S. (2020). Assessing the predictive nature of teacher and student writing self-regulation discrepancy. _Frontline Learning Research_, _8_(4), 52. https://doi.org/10.14786/flr.v8i4.505

+ Gellock, J., __Ekholm, E.__, Greenhalgh, G., LeCrom, C., Reina, C., & Kudesia, R. (2019). Women’s lacrosse players’ perceptions of teammate leadership: Examining athlete leadership behaviors, attributes, and interactions. _Journal of Athlete Development and Experience, 1(2)_, 2. https://scholarworks.bgsu.edu/jade/vol1/iss2/2.  

+ Zumbrunn, S., Marrs, S., Broda, M., __Ekholm, E.__, Jackson, L., & DeBusk-Lane, M. (2019). Toward a more complete understanding of writing enjoyment: A mixed methods study of elementary students. _AERA Open, 5(2)_, https://doi.org/10.1177/2332858419850792.

+ Broda, M., Tucker, S., __Ekholm, E.__, Johnson, T., & Liang, Q. (2019).  Small fingers, big data: Preschoolers’ subitizing speed and accuracy during interactions with multi-touch technology.  _The Journal of Educational Research, 112(2)_, 211-222. https://doi.org/10.1080/00220671.2018.1486281.

+ __Ekholm, E.__ & Chow. J. C. (2018). Addressing publication bias in educational psychology. _Translational Issues in Psychological Science, 4(4)_, 425-439. http://dx.doi.org/10.1037/tps0000181.

+ Broda, M., __Ekholm, E.__, Schneider, B., & Hutton, A. (2018). Teachers’ social networks, college-going practices, and the diffusion of a school-based reform initiative. _SAGE Open_. https://doi.org/10.1177/2158244018817397.

+ Chow, J.C., __Ekholm, E.__, & Coleman, H. (2018). Does oral language underpin the development of later behavior problems? A longitudinal meta-analysis. _School Psychology Quarterly, 33(3)_, 337-349. http://dx.doi.org/10.1037/spq0000255.

+ Chow, J.C., & __Ekholm, E.__ (2018). Do published studies yield larger effect sizes than unpublished studies in education and special education? A meta-review. _Educational Psychology Review, 30(3)_, 727-744. https://doi.org/10.1007/s10648-018-9437-7.

+ Chow, J. C., & __Ekholm, E.__ (2018). Language domains differentially predict mathematics performance in young children.  _Early Childhood Research Quarterly, 46_, 179-186. https://doi.org/10.1016/j.ecresq.2018.02.011

+ __Ekholm, E.__, Zumbrunn, S. & DeBusk-Lane, M. (2018). Clarifying an elusive construct: A systematic review of writing attitudes. _Educational Psychology Review, 30(3)_, 827-856. https://doi.org/10.1007/s10648-017-9423-5.

+ __Ekholm, E.__ (2017). Ethical concerns of using texts involving death in the English classroom. _English Journal, 107(2)_, 25-30.

+ Zumbrunn, S., __Ekholm, E.__, Stringer, J. K., McKnight, K., & DeBusk-Lane, M. (2017). Student experiences with writing: Taking the temperature of the classroom. _The Reading Teacher, 70(6)_, 667-677. https://doi.org/10.1002/trtr.1574.

+ __Ekholm, E.__, Zumbrunn, S., & Conklin, S. (2015). The relation of college student self-efficacy toward writing and writing self-regulation aptitude: writing feedback perceptions as a mediating variable. _Teaching in Higher Education, 20(2)_, 197-207. https://doi.org/10.1080/13562517.2014.974026.

<br/>

#### Other Publications

##### Fiction and Humor

+ __Ekholm, E__. [“If You Take My Survey, I’ll Let You Watch Me Cut My Finger Off.”](https://www.mcsweeneys.net/articles/if-you-take-my-survey-ill-let-you-watch-me-cut-my-finger-off) McSweeney’s Internet Tendency (June 7, 2016).

+ __Ekholm, E.__ [“Call for Submissions for APA’s Annual Conference, Sponsored by Shark Week.”](http://www.mcsweeneys.net/articles/call-for-submissions-for-apas-annual-conference-sponsored-by-shark-week)  McSweeney’s Internet Tendency (August 11, 2014).  

##### Book Reviews

+ __Ekholm, E.__ (September, 2016).  [A review of Kelly Gallagher’s _In the Best Interests of Students_.](http://www.ncte.org/library/NCTEFiles/Resources/Journals/EJ/1061_sep2016/EJ1061Reviews.pdf)

##### Other

+ Guest blog post, AERA Motivation SIG Blog, __Ekholm, E.__ (2018). [“What Motivation Researchers Can Learn from Professional Sports Teams.”](http://motsig.org/what-motivation-researchers-can-learn-from-professional-sports-teams/) November 6, 2018. 

<br/>

#### Conference Presentations & Invited Talks
_Only conference presentations since 2018 included_
 + __Ekholm, E.__ (November, 2023). [The Opportunities and Challenges of Using AI in the Classroom](https://docs.google.com/presentation/d/1F0VRkuDmlgj2Fuk4c5sSPEQDI0YIh8Ic3UPLDz31OM8/edit?usp=sharing). Session delivered as part of the Randolph-Macon College Education Department Fall 2023 Teacher Professional Development Series.

+ __Ekholme, E.__ (June, 2023). [Using AI to Generate Data-Driven Lesson Plans](https://docs.google.com/presentation/d/1MKi0Fjj39JH4y3P-z28v3KM7tkU9bPuNIVN-Rq-YliM/edit?usp=sharing). Session presented at the annual Metropolitan Educational Research Consortium (MERC) conference, Richmond, VA.

+ __Ekholm, E.__ (May, 2022). [Data Viz Tips & Tricks](https://github.com/ekholme/data_viz_tips). Invited talk presented to the Educational Research & Evaluation Network (EREN).

+ __Ekholme, E.__, & Fox, P. (October, 2021). Using machine learning to support student attendance practices. Session presented at the annual [Metropolitan Educational Research Consortium (MERC) conference](https://merc.soe.vcu.edu/conference/program/2021/), Richmond, VA. Video available [here](https://www.youtube.com/watch?v=gbTfelMWMiY) (~27:30 timestamp).

+ __Ekholm, E.__, & Zumbrun, S. (April, 2020). Investigating relations between writers’ emotional experiences and attention regulation: A daily diary study. Paper presented at the American Educational Research Association (AERA) Annual Meeting, San Francisco, CA.

+ __Ekholm, E.__, Zumbrunn, S., Broda, M., & Luther, T. C. (April, 2019). The development of student writing feedback attitudes in grades 3-7: A latent growth analysis. Poster presented at the American Educational Research Association (AERA) Annual Meeting, Toronto, Canada.

+ Zumbrunn, S., Broda, M., Marrs, S., & __Ekholm, E.__ (April, 2019). The complexities and challenges of understanding individual differences and the development of multiple dimensions of writing self-efficacy. Poster presented at the American Educational Research Association (AERA) Annual Meeting, Toronto, Canada.

+ Broda, M., __Ekholm, E.__, Hutton, C., & Schneider, B. (April, 2019). Teachers’ social networks, college-going practices, and the diffusion of a school-based reform initiative. Paper presented at the American Educational Research Association (AERA) Annual Meeting, Toronto, Canada.

+ Zumbrunn, S., Broda, M., __Ekholm, E.__, & Luther, T. C. (April, 2019). RoboCogger: Using mobile technology to assess and increase student writing metacognition, motivation, and performance. Paper presented at the American Educational Research Association (AERA) Annual Meeting, Toronto, Canada.

+ Broda, M., __Ekholm, E.__, & Zumbrunn, S. (October, 2018). Are we grading the “write” stuff? The relationship between teachers’ expectations, students’ self-regulation, and writing achievement. Paper presented at the CREATE Conference, Williamsburg, VA.

+ Zumbrunn, S., Marrs, S., Malmberg, L., __Ekholm, E.__, Broda, M., & DeBusk-Lane, M. (August, 2018). Individual differences and the development of multiple dimensions of writing self-efficacy. Paper presented at the International Conference of the EARLI Special Interest Group on Writing, Antwerp, Belgium.

+ __Ekholm, E.__, Zumbrunn, S., Hope, S., & Stim, H. (April, 2018). Teachers’ writing beliefs and instructional practices: A mixed-methods study. Poster presented at the American Educational Research Association (AERA) Annual Meeting, New York City, NY.

+ Marrs, S., __Ekholm, E.__, & Zumbrunn, S. (April, 2018). Exploring profiles of student perceptions of writing feedback. Roundtable presented at the American Educational Research Association (AERA) Annual Meeting, New York City, NY.

+ Tucker, S., Broda, M., __Ekholm, E.__, Johnson, T., & Liang, Q. (April, 2018). Preschoolers’ subitizing speed and accuracy during interactions with multi-touch technology. Roundtable presented at the American Educational Research Association (AERA) Annual Meeting, New York City, NY.

+ Chow, J.C. & __Ekholm, E.__ (February, 2018). Estimating the magnitude of the difference between published and unpublished studies in special education: A metareview. Poster presented at the Council for Exceptional Children Annual Convention, Tampa, FL.