---
title: "9-28-23 Daily Note"
date: 2023-09-28
description: |
  doing things ethically vs doing ethical things
categories: [Ethics, AI]
---

I read an [opinion piece](https://link.springer.com/article/10.1007/s40593-023-00352-3) about AI in education today, and the author stressed that researchers need to consider the difference between "doing things ethically" and "doing ethical things." I hadn't thought much about the difference between these two things before, but it does seem striking now that he raised it.

My interpretation of the difference here is that "doing ethical things" requires carefully contemplating the end-state of your research/product/project/whatever, and the potential consequences of this end-state, before embarking on a project. That is, it requires some determination at the outset of whether the whole endeavor is ethical.

"Doing things ethically," on the other hand, doesn't seem to require this. Rather, to "do things ethically," researchers/developers/whoever just need to ensure that the process is ethical -- that participants are treated fairly, proper disclosures are made, etc.

For example, when developing an AI application, a company could "do things ethically" by paying its employees fairly, abiding by all relevant laws and regulations when gathering training data (which isn't always the case), treat any research participants beneficently, etc. But this doesn't mean that the application the company is creating is, in itself, ethical. What if it were an education application that used poor pedagogical practices? What if it forced automation of decisions that should be left up to teachers? This may not be an ethical application, even if the process for getting to it was ethical.

I really appreciated the point made here, and it's something I want to think on more as I engage more in the AI world.