---
title: "9-27-23 Daily Note"
description: |
  Suitcase carries for core stability
date: today
categories: [Fitness]
---

According to [Squat University](https://www.youtube.com/watch?v=LJaq4BS7KpE), suitcase carries with a kettlebell are a great core workout.

The video linked above says that, to do them properly, you should brace your core while carrying (you can test this by poking your finger into your obliques), breathe through your diaphragm, and try to keep your torso level as you carry a kettlebell on one side.

The weight of the kettlebell doesn't have to be super heavy either, I don't think. And to make the exercise more difficult, you can either add weight or carry the kettlebell bell-side-up (still holding the handle), which will require more coordination and activation to stabilize it.

The exercise doesn't take long, either -- the video suggests 3-4 sets of ~45-60 second carries per side.

I should probably start incorporating this into my workout as auxiliary work -- it shouldn't be difficult to superset this into basically any workout I do.
